//
//  ListPresenter.swift
//  DesafioCielo
//
//  Created by Gustavo Melki Leal on 19/09/2018.
//  Copyright (c) 2018 Gustavo Melki Leal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPresentationLogic {
  func presentCharacters(response: List.Response)
}

class ListPresenter: ListPresentationLogic {
  weak var viewController: ListDisplayLogic?
  
  // MARK: Do something
  
  func presentCharacters(response: List.Response) {
    let viewModel = List.ViewModel(characters: response.characters)
    viewController?.displayCharacters(viewModel: viewModel)
  }
}
